version: '3.7'
services:
  vuldetector:
    image: vuldetector
    container_name: vuldetector
    hostname: vuldetector
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - path/to/repo:/code

